### ISSUE TITLE
"Something went wrong" UNEXPECTED FATAL EXCEPTION - Networking

### ISSUE THREAD

**Issue by kramarz89** [Spec-ify/specify#57]
Hi,

When running the program, something goes wrong and doesnt collect all the data.

here is the debug file:

```
[3.0005]     [Information] --- DEBUG LOG STARTED 12:41:07 ---                              :
[4.5021]     [Information] RedactUsername: True                                            :
[4.5021]     [Information] RedactOneDriveCommercial: True                                  :
[4.5021]     [Information] DontUpload: False                                               :
[4.5021]     [Information] LocalCulture: False                                             :
[9.512]     [Region Start] --- Main Region Start ---                                       : Main
[9.512]     [Region Start] --- Networking Region Start ---                                 : Networking
[9.512]     [Region Start] --- Hardware Region Start ---                                   : Hardware
[10.5114]   [Region Start] --- System Region Start ---                                     : System
[10.5114]   [Region Start] --- Security Region Start ---                                   : Security
[14.0185]    [Information] Task Started: GetEnvironmentVariables                           : System
[14.0185]    [Information] Task Started: GetTemps                                          : Hardware
[15.0237]    [Information] Task Completed: GetEnvironmentVariables - Runtime: 2.5107       : System
[16.0281]    [Information] Security WMI Information Retrieved.                             : Security
[16.0281]    [Information] SecureBoot Information Retrieved.                               : Security
[16.0281]    [Information] Task Started: GetSystemWMIInfo                                  : System
[41.0542]          [ERROR] !!! UNEXPECTED FATAL EXCEPTION !!!                              : Networking
[41.0542]          [ERROR] !!! System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at specify_client.data.Utils.GetWmi(String cls, String selected, String ns)
   at specify_client.data.Cache.<MakeNetworkData>d__251.MoveNext() !!!  : Networking
[76.7239]    [Information] Main WMI Data retrieved.                                        : Main
[78.7248]     [Region End] --- Main Region End - Total Time: 69.2128ms ---                 : Main
[397.0135]   [Information] TPM Information Retrieved.                                      : Security
[397.0135]   [Information] UAC Information retrieved.                                      : Security
[397.0135]    [Region End] --- Security Region End - Total Time: 386.5021ms ---            : Security
[550.5663]   [Information] Task Completed: GetSystemWMIInfo - Runtime: 534.5382            : System
[552.6606]   [Information] Task Started: CheckCommercialOneDrive                           : System
[552.6606]       [Warning] RedactOneDriveCommercial setting disabled. OneDriveCommercial variable not found. : System
[552.6606]   [Information] Task Completed: CheckCommercialOneDrive - Runtime: 0            : System
[553.6683]   [Information] Task Started: GetInstalledApps                                  : System
[556.448]    [Information] Task Completed: GetInstalledApps - Runtime: 2.7797              : System
[558.4659]   [Information] Task Started: GetScheduledTasks                                 : System
[905.6288]   [Information] Task Completed: GetScheduledTasks - Runtime: 347.1629           : System
[907.6344]   [Information] Task Started: GetStartupTasks                                   : System
[913.6348]   [Information] Task Completed: GetStartupTasks - Runtime: 6.0004               : System
[915.1461]   [Information] Task Started: RegistryCheck                                     : System
[916.1508]   [Information] Task Completed: RegistryCheck - Runtime: 1.0047                 : System
[916.1508]   [Information] Task Started: GetMicroCodes                                     : System
[917.1506]   [Information] Task Completed: GetMicroCodes - Runtime: 0.9998                 : System
[918.1511]   [Information] Task Started: GetStaticCoreCount                                : System
[955.2183]   [Information] Task Completed: GetStaticCoreCount - Runtime: 37.0672           : System
[962.2659]   [Information] Task Started: GetBrowserExtensions                              : System
[1061.2081]  [Information] Task Completed: GetBrowserExtensions - Runtime: 98.9422         : System
[1064.7174]  [Information] Task Started: GetMiniDumps                                      : System
[1064.7174]  [Information] No current dumps found.                                         : System
[1064.7174]  [Information] Task Completed: GetMiniDumps - Runtime: 0                       : System
[1065.7179]  [Information] Task Started: GetDefaultBrowser                                 : System
[1066.7229]  [Information] Task Completed: GetDefaultBrowser - Runtime: 1.005              : System
[1068.7235]  [Information] Task Started: GetProcesses                                      : System
[1075.2318]      [Warning] System Data: Could not get the EXE path of vmmemCmZygote (14368) : System
[1077.2381]  [Information] Task Completed: GetProcesses - Runtime: 8.5146                  : System
[1077.2381]   [Region End] --- System Region End - Total Time: 1066.7267ms ---             : System
[1726.2884]  [Information] Task Completed: GetTemps - Runtime: 1713.7754                   : Hardware
[1727.2543]  [Information] Task Started: GetHardwareWmiData                                : Hardware
[3995.0217]  [Information] Task Completed: GetHardwareWmiData - Runtime: 2267.7674         : Hardware
[3997.0283]  [Information] Task Started: GetMonitorInfo                                    : Hardware
[4026.2858]  [Information] Task Completed: GetMonitorInfo - Runtime: 29.2575               : Hardware
[4029.2848]  [Information] Task Started: GetMemoryInfo                                     : Hardware
[4032.2859]  [Information] Task Completed: GetMemoryInfo - Runtime: 3.0011                 : Hardware
[4034.7965]  [Information] Task Started: GetDiskDriveData                                  : Hardware
[5090.816]   [Information] Task Completed: GetDiskDriveData - Runtime: 1056.0195           : Hardware
[5092.8151]  [Information] Task Started: GetBatteryData                                    : Hardware
[5392.5558]  [Information] Task Completed: GetBatteryData - Runtime: 299.7407              : Hardware
[5392.5558]   [Region End] --- Hardware Region End - Total Time: 5383.0438ms ---           : Hardware
[5397.0729]  [Information] Serialization starts                                            :
[5402.0719]  [Information] Monolith created                                                :
[5453.8956]  [Information] Monolith serialized                                             :
[5460.4087]  [Information] Username Redacted from report                                   :
[5470.9253]  [Information] File sent. Awaiting HTTP Response.                              :
[5736.3396]  [Information] File uploaded successfully: https://spec-ify.com/profile/28ecb4ca :
[5757.4451]        [ERROR] !!! Logging completed with unfinished region: Networking !!!    : Networking
[5757.4451]  [Information] Main Data Errors: 0                                             :
[5757.4451]  [Information] System Data Errors: 0                                           :
[5757.4451]  [Information] Security Data Errors: 0                                         :
[5757.4451]  [Information] Networking Data Errors: 3                                       :
[5757.4451]  [Information] Hardware Data Errors: 0                                         :
[5757.4451]  [Information] Misc Data Errors: 0                                             :
[5757.4451]  [Information] Total Elapsed Time: 5757.4451                                   :
[5757.4451]  [Information] --- DEBUG LOG FINISHED 12:41:12 ---                             :

```

**Comment by kramarz89** [comment]
> Can you tick "Don't Upload" and provide the specify_specs.json it creates, please?

Affraid I cannot do that anymore :( I've reinstalled the system and now it's working fine. Guess we should close this then
